#!/bin/bash

set -e

catCommonScripts() {

    local dir="$(dirname "$1")"

    if [ "$dir" != "." ]; then

        catCommonScripts "$dir"

        local commonScript="$dir/common.sh"
        if [ -f "$commonScript" ]; then
            >>"$out" cat "$commonScript"
            >>"$out" echo
        fi

    fi

}

makeScript() {

    device="$1"
    out="${2:-build/lanchon-repit-$device.sh}"

    deviceScript="$(find device -name "$device.sh")"

    if [ "$device" == "common" ] || [ ! -f "$deviceScript" ]; then
        >&2 echo "error: invalid device: '$device'"
        exit 1
    fi

    rm -f "$out"

    >>"$out" cat repit.sh
    >>"$out" echo
    >>"$out" cat repit-par-tools.sh
    >>"$out" echo

    >>"$out" cat repit-fs-ext4.sh
    >>"$out" echo
    >>"$out" cat repit-fs-vfat.sh
    >>"$out" echo
    >>"$out" cat repit-fs-f2fs.sh
    >>"$out" echo
    >>"$out" cat repit-fs-swap.sh
    >>"$out" echo
    >>"$out" cat repit-fs-raw.sh
    >>"$out" echo

    catCommonScripts "$deviceScript"
    >>"$out" cat "$deviceScript"
    >>"$out" echo

    >>"$out" echo "#####################################################"
    >>"$out" echo
    >>"$out" printf 'deviceName=%q\n' "$device"
    >>"$out" echo
    >>"$out" echo 'main "$@"'

}

makeScript "$@"
