#!/bin/bash

set -e

device="$1"
conf="$2"

if [ -e run.conf ]; then
    source run.conf
fi

./make-script "$device"
script="build/lanchon-repit-$device.sh"

adb push "$script" /tmp/repit.sh
echo

#adb shell sh -c ".\ /tmp/flashize/env/setup\ ;\ .\ /tmp/repit.sh\ /tmp/lanchon-repit-00000000-$conf-$device.zip"

adb shell <<EOF
. /tmp/flashize/env/setup &&
. /tmp/repit.sh /tmp/lanchon-repit-00000000-$conf-$device.zip
exit
EOF
