#!/bin/bash

set -e

unsignedZip="repit-dump-unsigned.zip"
signedZip="repit-dump.zip"

rm -f "$unsignedZip"
rm -f "$signedZip"

flashize-env dump.sh ../env/arm.zip "$unsignedZip" repit-dump.log
signapk -w ../key/testkey.x509.pem ../key/testkey.pk8 "$unsignedZip" "$signedZip"

#rm "$unsignedZip"
